Repository cert-manager/infrastructure, pull requests merged in 2022-01, with the labels that each got.

#8 Add initial details about services we use
  README.md
Labels: dco-signoff: yes, lgtm, approved, size/M

#12 Add note about our twitter account
  README.md
Labels: dco-signoff: yes, lgtm, size/XS, approved

#10 Add note about the cert-manager youtube account
  README.md
Labels: dco-signoff: yes, size/XS, approved

#11 Mention that we don't know who has access to the main creds for the main Netlify account
  README.md
Labels: dco-signoff: yes, lgtm, size/XS, approved

#13 Zapier
  README.md
Labels: dco-signoff: yes, lgtm, size/XS, approved
