Repository cert-manager/infrastructure, pull requests merged in 2024-07, with the labels that each got.

#49 Update wording on how to access algolia
  README.md
Labels: dco-signoff: yes, lgtm, size/XS, approved

#50 Add Netlify DNS records and split config into two files
  gcp/general_dns.tf
  gcp/general_dns_cert-manager.tf
  gcp/general_dns_trust-manager.tf
Labels: dco-signoff: yes, size/L, lgtm, approved

#51 Update README with infrastructure changes
  README.md
Labels: dco-signoff: yes, lgtm, size/S, approved

#52 Enable logging and monitoring for the GKE clusters
  gcp/modules/gcp-cluster/main.tf
Labels: dco-signoff: yes, lgtm, approved, size/M
