Repository cert-manager/infrastructure, pull requests merged in 2024-05, with the labels that each got.

#40 Zoom and CNCF calendar: explain how these are created and managed
  README.md
Labels: dco-signoff: yes, lgtm, size/XS, approved

#39 Remove unused infrastructure
  gcp/release_imported.tf
Labels: dco-signoff: yes, lgtm, approved, size/M

#41 Terraform prow static ip
  gcp/clusters.tf
  gcp/general_dns.tf
  gcp/modules/gcp-cluster/main.tf
  gcp/modules/gcp-cluster/variables.tf
  gcp/trusted_prow_ip.tf
Labels: dco-signoff: yes, lgtm, size/S, approved

#34 Add base for documentation of our gcp terraform process
  README.md
  gcp/README.md
Labels: dco-signoff: yes, lgtm, approved, size/M

#43 Tear down kubecon paris booth infra
  gcp/general_dns.tf
  gcp/general_kubecon_booth.tf
Labels: dco-signoff: yes, lgtm, approved, size/M

#45 readme: talk about the cert-manager 1Password team
  README.md
Labels: dco-signoff: yes, lgtm, approved, size/M
